import {
  Wrench,
  Ghost,
  Download,
  Share,
  Video,
  Smartphone,
  Home,
  Clapperboard,
  Zap,
  ClipboardList,
  Pencil,
  Type,
  VolumeX,
  MessageCircle,
  Hash,
  Flame,
  MessageSquare,
  Trophy,
  Volume2,
  Dumbbell,
  PenLine,
  GraduationCap,
  Rocket,
  Camera,
  Award,
  CalendarCheck,
  Target,
  Swords,
  Star,
  Crown,
  Settings,
  BarChart3,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  wrench: Wrench,
  ghost: Ghost,
  download: Download,
  share: Share,
  video: Video,
  smartphone: Smartphone,
  home: Home,
  clapperboard: Clapperboard,
  zap: Zap,
  "clipboard-list": ClipboardList,
  pencil: Pencil,
  type: Type,
  "volume-x": VolumeX,
  "message-circle": MessageCircle,
  hash: Hash,
  flame: Flame,
  "message-square": MessageSquare,
  trophy: Trophy,
  volume2: Volume2,
  dumbbell: Dumbbell,
  "pen-line": PenLine,
  "graduation-cap": GraduationCap,
  rocket: Rocket,
  camera: Camera,
  award: Award,
  "calendar-check": CalendarCheck,
  target: Target,
  swords: Swords,
  star: Star,
  crown: Crown,
  settings: Settings,
  "bar-chart": BarChart3,
};

export function getIcon(name: string): LucideIcon | null {
  return ICON_MAP[name] || null;
}
